Knowts/config/routes.rb
Rails.application.routes.draw do
  resources :workspaces

  devise_for :users
  resources :users

  root 'home#index'
  get '/index' => 'home#index'
  get '/about' => 'home#about'
  get '/sitemap' => 'home#sitemap'
  get '/login' => 'accounts#sign_in'
  get '/loggedin' => 'accounts#signed_in'
  get '/signup' => 'accounts#register'
  get '/logout' => 'accounts#sign_out'
  get '/app' => 'workspaces#index'

  resources :workspaces do
    resources :lists
  end

  resources :lists do
    resources :items
  end

  post 'workspaces/:id/adduser' => 'workspaces#adduser'
  delete 'workspaces/:w_id/lists/:l_id/items/:id/removeme' => 'items#removeme'
  post 'workspaces/:w_id/lists/:l_id/items/:id/addme' => 'items#addme'
  post 'workspaces/:w_id/items/:id/toggledone' => 'items#toggledone'
  delete 'users/:u_id/workspaces/:w_id/removeuser' => 'workspaces#removeuser'
  delete 'workspaces/:w_id/:u_id/removeworkspace' => 'workspaces#removeworkspace'

end

Knowts/app/models/list.rb
class List < ActiveRecord::Base
  #destroy the item upon deleting the list
  has_many :items, dependent: :destroy
  belongs_to :workspace

  validates :name, presence: true, length: {minimum: 3}
end

Knowts/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @list = List.find_by_id params[:id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You don't have the permission to edit the list."
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    workspace = Workspace.find_by_id params[:workspace_id]
    if not workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You don't have the permission for this workspace."
      return
    end
    @list = workspace.lists.create(list_params)
    workspace.save

    respond_to do |format|
      if @list.save
        format.html { redirect_to workspace, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: workspace }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    @list = List.find_by_id params[:id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to :back, alert: "You don't have the permission to edit the list."
      return
    end
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find_by_id params[:id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You don't have the permission to delete the list."
      return
    end
    @list.destroy
    respond_to do |format|
      format.html { redirect_to @workspace, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description)
    end
end

Knowts/app/helpers/lists_helper.rb
module ListsHelper
end

Knowts/app/views/lists/_form.html.erb
<%= form_for [@workspace, @list], url: workspace_lists_path do |f| %>
  <% if @list.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="list-form">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Create List", :class=> "button" %>
  </div>
  </div>
<% end %>

Knowts/app/views/lists/edit.html.erb
<div class="list-controller-div">
  <div class="list-links">
    <%= link_to 'Show', @list %> |
    <%= link_to 'Back', lists_path %>
  </div>
  <h1>Editing list</h1>

<%= form_for @list do |f| %>
    <% if @list.errors.any? %>
        <div class="error_explanation">
          <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
          <ul>
            <% @list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="list-form">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="actions">
        <%= f.submit "Edit List", :class=> "button" %>
      </div>
    </div>
<% end %>
</div>

Knowts/app/views/lists/index.html.erb
<div class="list-controller-div">

<h1>Listing lists</h1>

<table class="lists-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
</div>

Knowts/app/views/lists/new.html.erb
<div class="list-controller-div">
<h1>New list</h1>

  <%= form_for [@workspace, @list], url: workspace_lists_path do |f| %>
      <% if @list.errors.any? %>
          <div class="error_explanation">
            <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
            <ul>
              <% @list.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="list-form">
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_field :description %>
        </div>
        <div class="actions">
          <%= f.submit "Create List", :class=> "button" %>
        </div>
      </div>
  <% end %>

</div>

Knowts/app/views/lists/show.html.erb
<div class="list-controller-div">
  <div class="list-links">
    <%= link_to 'Edit', edit_list_path(@list) %> |
    <%= link_to 'Back', lists_path %>
  </div>
  <h1>List information</h1>

  <p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

</div>