Knowts/config/routes.rb
Rails.application.routes.draw do
  resources :workspaces

  devise_for :users
  resources :users

  root 'home#index'
  get '/index' => 'home#index'
  get '/about' => 'home#about'
  get '/sitemap' => 'home#sitemap'
  get '/login' => 'accounts#sign_in'
  get '/loggedin' => 'accounts#signed_in'
  get '/signup' => 'accounts#register'
  get '/logout' => 'accounts#sign_out'
  get '/app' => 'workspaces#index'

  resources :workspaces do
    resources :lists
  end

  resources :lists do
    resources :items
  end

  post 'workspaces/:id/adduser' => 'workspaces#adduser'
  delete 'workspaces/:w_id/lists/:l_id/items/:id/removeme' => 'items#removeme'
  post 'workspaces/:w_id/lists/:l_id/items/:id/addme' => 'items#addme'
  post 'workspaces/:w_id/items/:id/toggledone' => 'items#toggledone'
  delete 'users/:u_id/workspaces/:w_id/removeuser' => 'workspaces#removeuser'
  delete 'workspaces/:w_id/:u_id/removeworkspace' => 'workspaces#removeworkspace'

end

Knowts/app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :list

  validates :due, presence: true
  validates :content, presence: true, length: {within: 3..150}
end

Knowts/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @list = List.find_by_id params[:list_id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to view the items"
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to view the item"
    end
  end

  # GET /items/new
  def new
    @list = List.find_by_id params[:list_id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to create item in this workspace"
    end
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to edit the items"
    end
  end

  # POST /items
  # POST /items.json
  def create
    @list = List.find_by_id params[:list_id]
    @workspace = @list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to create the items"
      return
    end
    @item = @list.items.create item_params
    @list.save
    respond_to do |format|
      if @item.save
        format.html { redirect_to @workspace, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission to edit the items"
      return
    end
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @workspace, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @workspace }
      else
        format.html { render :edit }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  def addme
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "You have no permission add yourself to the item."
      return
    end
    if not @item.users.include? current_user
      @item.users << current_user
      @item.save
      redirect_to @workspace, notice: 'User added to item'
    else
      redirect_to @workspace
    end
  end

  def removeme
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "Denied permission"
      return
    end
    if @item.users.include? current_user
      @item.users.delete(current_user)
      @item.save
      redirect_to @workspace, notice: 'User removed from item'
    else
      redirect_to @workspace
    end
  end

  def toggledone
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "Denied permission"
      return
    end

    # this is a hack, because ruby complains about item.completed = not item.completed
    @item.completed = !@item.completed
    @item.save
    redirect_to @workspace
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find_by_id params[:id]
    @workspace = @item.list.workspace
    if not @workspace.users.include? current_user
      redirect_to workspaces_path, alert: "Denied permission"
      return
    end
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @workspace, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:content, :due)
    end
end

Knowts/app/helpers/items_helper.rb
module ItemsHelper
end

Knowts/app/views/items/_form.html.erb
<%= form_for [@list, @item], url: list_item_path do |f| %>
    <% if @item.errors.any? %>
        <div class="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_field :content %>
    </div>
    <div class="field">
      <%= f.label :due %><br>
      <%= f.datetime_select :due %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

Knowts/app/views/items/edit.html.erb
<div class="edit_workspace_form">
  <div class="route">
    <%= link_to 'Back', @workspace %>
  </div>
  <h1>Editing item</h1>

  <%= form_for [@list, @item], url: list_item_path do |f| %>
      <% if @item.errors.any? %>
          <div class="error_explanation">
            <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_field :content %>
      </div>
      <div class="field">
        <%= f.label :due %><br>
        <%= f.datetime_select :due %>
      </div>
      <div class="actions">
        <%= f.submit "Edit", :class => "button" %>
      </div>
  <% end %>

</div>

Knowts/app/views/items/index.html.erb
<div class="item-content">
<div class="item-links">
 <%= link_to "Back to workspace", workspace_path(@workspace) %>
</div>
<h1 style="text-align: left; margin: 10px;">Listing items</h1>

<table class="items-table">
  <thead>
    <tr>
      <th>Content</th>
      <th>Due</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list.items.each do |item| %>
      <tr>
        <td><%= item.content %></td>
        <td><%= item.due %></td>
        <td><%= item.completed %></td>
        <td><%= link_to "Show", list_item_path(@list, item)%></td>
        <td><%= link_to "Edit", edit_list_item_path(@list, item)%></td>
        <td><%= link_to "Delete", "/lists/#{@list.id}/items/#{item.id}", method: 'delete'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

Knowts/app/views/items/new.html.erb
<div class = "item-form">
<h1>New item</h1>

<%= form_for [@list, @item], url: list_items_path do |f| %>
    <% if @item.errors.any? %>
        <div class="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="item-form-content">
      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_field :content %>
      </div>
      <div class="field">
        <%= f.label :due %><br>
        <%= f.datetime_select :due %>
      </div>
      <%= f.submit "Create", :class => "button" %>
    </div>
<% end %>
</div>

Knowts/app/views/items/show.html.erb
<div class="item-content" style="font-size: 30px">
  <div class="item-links">
    <%= link_to "Back to workspace", workspace_path(@workspace) %>
  </div>
  <h1 style="font-size: 40px"> Showing item:</h1>
  <p class="item-content-name">
  <strong>Content:</strong>
  <%= @item.content %>
</p>
<br/>
<p>
  <strong>Due:</strong>
  <%= @item.due %>
</p>
  <br/>

  <p>
    <strong>Completed:</strong>
    <%= @item.completed %>
  </p>

</div>