Knowts/config/routes.rb
Rails.application.routes.draw do
  resources :workspaces

  devise_for :users
  resources :users

  root 'home#index'
  get '/index' => 'home#index'
  get '/about' => 'home#about'
  get '/sitemap' => 'home#sitemap'
  get '/login' => 'accounts#sign_in'
  get '/loggedin' => 'accounts#signed_in'
  get '/signup' => 'accounts#register'
  get '/logout' => 'accounts#sign_out'
  get '/app' => 'workspaces#index'

  resources :workspaces do
    resources :lists
  end

  resources :lists do
    resources :items
  end

  post 'workspaces/:id/adduser' => 'workspaces#adduser'
  delete 'workspaces/:w_id/lists/:l_id/items/:id/removeme' => 'items#removeme'
  post 'workspaces/:w_id/lists/:l_id/items/:id/addme' => 'items#addme'
  post 'workspaces/:w_id/items/:id/toggledone' => 'items#toggledone'
  delete 'users/:u_id/workspaces/:w_id/removeuser' => 'workspaces#removeuser'
  delete 'workspaces/:w_id/:u_id/removeworkspace' => 'workspaces#removeworkspace'

end

Knowts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowts</title>
  <link href='http://fonts.googleapis.com/css?family=Gilda+Display%7CPoiret+One%7CSpecial+Elite' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/css/about.css">
  <link rel="stylesheet" href="/css/sitemap.css">
  <link rel="stylesheet" href="/css/login.css">
</head>
<body>

<div class="header">
  <div class="left">
    <%= link_to "Knowts", root_path %>
  </div>
  <div class="right">
    <div> <%= link_to "Home", root_path %> </div>
    <% if not user_signed_in? %>
        <div> <%= link_to "About", about_path %> </div>
        <div> <%= link_to "Login", login_path %> </div>
        <div> <%= link_to "Signup", signup_path %> </div>
    <% else %>
        <div><%= link_to "Workspaces", workspaces_path %> </div>
        <div><%= link_to "User Account", user_path(current_user) %> </div>
        <%= form_tag('/users/sign_out', method: 'delete', id: 'signout_form') do %>
            <div id="sign_out_button">Logout</div>
        <% end %>
    <% end %>
  </div>
</div>
<div class="content">
  <div class="alert"><%= alert %></div>
  <p class="notice"><%= notice %></p>

  <%= yield %>
  <footer>
    <span>
      <%= link_to "Sitemap", sitemap_path %>
    </span>
    <span>Website designed &amp; developed by Knowts Ltd.</span>
    <span>
      <a href="/simplecov/"> Test Coverage</a>
    </span>
    <div class="validation-links">
      <a style="text-decoration: none" href="http://validator.w3.org/check/referer">
        <img style="border:0;width:32px;height:32px;padding-top: 10px"
             src="/images/HTML5_Logo_32.png"/>
      </a>
      <a style="text-decoration: none" href="http://jigsaw.w3.org/css-validator/check/referer">
        <img style="border:0;width:88px;height:31px"
             src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
             alt="Valid CSS!" />
      </a>
    </div>
  </footer>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>