Knowts/config/routes.rb
Rails.application.routes.draw do
  resources :workspaces

  devise_for :users
  resources :users

  root 'home#index'
  get '/index' => 'home#index'
  get '/about' => 'home#about'
  get '/sitemap' => 'home#sitemap'
  get '/login' => 'accounts#sign_in'
  get '/loggedin' => 'accounts#signed_in'
  get '/signup' => 'accounts#register'
  get '/logout' => 'accounts#sign_out'
  get '/app' => 'workspaces#index'

  resources :workspaces do
    resources :lists
  end

  resources :lists do
    resources :items
  end

  post 'workspaces/:id/adduser' => 'workspaces#adduser'
  delete 'workspaces/:w_id/lists/:l_id/items/:id/removeme' => 'items#removeme'
  post 'workspaces/:w_id/lists/:l_id/items/:id/addme' => 'items#addme'
  post 'workspaces/:w_id/items/:id/toggledone' => 'items#toggledone'
  delete 'users/:u_id/workspaces/:w_id/removeuser' => 'workspaces#removeuser'
  delete 'workspaces/:w_id/:u_id/removeworkspace' => 'workspaces#removeworkspace'

end

Knowts/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def signed_in
    if not user_signed_in?
      redirect_to login_path
    end

  end

  def sign_in
    if user_signed_in?
      redirect_to loggedin_path
    end
  end

  def sign_out
  end

  def register
    if user_signed_in?
      redirect_to loggedin_path
    end
  end



end

Knowts/app/helpers/accounts_helper.rb
module AccountsHelper
end

Knowts/app/views/accounts/register.html.erb
<div class="login_form">
  <h1> Sign Up </h1>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>


        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: "on" %>
        <br/>

        <%= f.label :email %><br />
        <%= f.email_field :email, autocomplete: "off" %>
        <br/>

        <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        <br/>

        <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        <br/>

        <%= f.submit "Sign up", :class => "button"  %>
    <% end %>
  <p> Have an account?
    <%= link_to "Login", login_path %>
    here.
  </p>
  <!--%= render "devise/shared/links" %-->

</div>

Knowts/app/views/accounts/sign_in.html.erb
<div class="login_form">
  <h1>Login</h1>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= f.label :email %>:<br />
        <%= f.email_field :email, autofocus: "on" %>
      <br />
      <%= f.label :password %>:<br />
        <%= f.password_field :password, autocomplete: "off" %>
      <br />

      <% if devise_mapping.rememberable? -%>
          <%= f.check_box :remember_me %> <%= f.label :remember_me %>
      <% end %>
      <br />

      <%= f.submit "Sign in", :class => "button" %>
  <% end %>
  <div id="error"></div>
  <p>Don't have an account?
    <%= link_to "Signup", signup_path %> here!
  </p>
</div>

Knowts/app/views/accounts/sign_out.html.erb
<div class="logout-page">
<h1> Log out </h1> <br>
<div class="logout-notice">
  You have successfully log out. <br/>
  Make sure to stay awesome!
  Hope to see you soon.
  </div>
<div class="logout-links">
  Click <%= link_to "here", root_path %> to return to Knowts! <br/>

</div>
</div>

Knowts/app/views/accounts/signed_in.html.erb
<div class="signed_in-page">
  <h1> Sign in </h1> <br>
  <div class="signed_in-notice">
    You have already signed in as <span class="signed_in-user"><%= current_user.email %> </span>
    <br/>
    <span style="font-weight: bold"> Not You? </span> <br>
    Click the logout button above to log out.
  </div>
  <div class="signed_in-links">
    Click <%= link_to "here", root_path %> to return to Knowts! <br/>

  </div>
</div>